server:
  port: 8080

spring:
  application:
    name: catalog-service

kafka:
  bootstrap-servers: localhost:9094

message-broker:
  topic:
    order-created: order.created.topic

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
        step: 5s
  tracing:
    enabled: true
    sampling:
      probability: 1.0

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  traces:
    exporter: otlp
  logs:
    exporter: otlp
  metrics:
    exporter: none

logging:
  level:
    com.observability: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.Metadata: WARN
    org.springframework.kafka: WARN
