receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

  resource:
    attributes:
      - action: insert
        key: service.name
        from_attribute: service.name

  transform/logs:
    log_statements:
      - context: log
        statements:
          - set(attributes["trace_id"], trace_id.string)
          - set(attributes["span_id"], span_id.string)

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]

    logs:
      receivers: [otlp]
      processors: [transform/logs, resource, batch]
      exporters: [otlphttp/loki]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]
