server:
  port: 8081

spring:
  application:
    name: order-service

catalog:
  base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
        step: 5s
  tracing:
    sampling:
      probability: 1.0

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  traces:
    exporter: otlp
  logs:
    exporter: otlp
  metrics:
    exporter: none

logging:
  level:
    com.observability: INFO
